export const ParamsKey = {
  token: 'token',
  email: 'email',
  password: 'password',
  verifyCode: 'verifyCode',
  newPassword: 'newPassword',
  oldPassword: 'oldPassword',
  nickname: 'nickname',
  phoneNumber: 'phoneNumber',
  action: 'action',
  gender: 'gender',
  account: 'account',
  endTime: 'endTime',
  startTime: 'startTime',
  rows: 'rows',
  device: 'device',
  gameCode: 'gameCode',
  method: 'method',
  uid: 'uid',
  date: 'date',
  coinUrl: 'coinUrl',
} as const;
